function FileData_Pairs(x)
{
x.t("introduce","i-spy");
x.t("managing","lists");
x.t("lists","glossary");
x.t("getting","started");
x.t("need","know");
x.t("results","managing");
x.t("high","order");
x.t("i-spy","1.0");
x.t("i-spy","describe");
x.t("conducting","searches");
x.t("conducting","identifier");
x.t("searches","high");
x.t("welcome","i-spy");
x.t("started","i-spy");
x.t("1.0","getting");
x.t("1.0","conducting");
x.t("1.0","online");
x.t("know","i-spy:");
x.t("viewing","results");
x.t("identifier","lookup");
x.t("i-spy:","i-spy");
x.t("online","help");
x.t("help","welcome");
x.t("help","following");
x.t("topics","introduce");
x.t("order","analysis");
x.t("following","topics");
x.t("lookup","conducting");
x.t("analysis","viewing");
x.t("describe","concepts");
x.t("concepts","need");
}
