function FileData_Pairs(x)
{
x.t("describes","perform");
x.t("advanced","queries");
x.t("reports.","topics");
x.t("overview","performing");
x.t("conducting","searches");
x.t("searches","conducting");
x.t("searches","section");
x.t("include:","search");
x.t("perform","advanced");
x.t("search","overview");
x.t("queries","generate");
x.t("section","describes");
x.t("section","include:");
x.t("loss","expression");
x.t("level","expression");
x.t("performing","ihc");
x.t("performing","clinical");
x.t("ihc","loss");
x.t("ihc","level");
x.t("generate","customized");
x.t("expression","query");
x.t("query","performing");
x.t("customized","reports.");
x.t("topics","section");
x.t("clinical","query");
}
