function FileData_Pairs(x)
{
x.t("create","patientdid");
x.t("queries.","icon");
x.t("related","topics.");
x.t("displays","demographic");
x.t("icon","ncia");
x.t("access","images");
x.t("list","further");
x.t("results","search");
x.t("results","clinical");
x.t("filter","queries.");
x.t("images","associated");
x.t("patientdid","list");
x.t("patient.","information");
x.t("further","filter");
x.t("search","results");
x.t("demographic","clinical");
x.t("viewing","results");
x.t("report","create");
x.t("report","displays");
x.t("report","access");
x.t("reports","viewing");
x.t("reports","clinical");
x.t("pathology","data");
x.t("given","patients.");
x.t("ncia","image");
x.t("data","given");
x.t("information","related");
x.t("image","column");
x.t("column","report");
x.t("patients.","clinical");
x.t("associated","patient.");
x.t("clinical","report");
x.t("clinical","reports");
x.t("clinical","pathology");
}
