function FileData_Pairs(x)
{
x.t("user","account");
x.t("support","logging");
x.t("getting","started");
x.t("getting","help");
x.t("obtain","help");
x.t("creating","user");
x.t("account","logging");
x.t("i-spy","procedures");
x.t("i-spy","1.0");
x.t("i-spy","provisions");
x.t("include:","creating");
x.t("logging","accepting");
x.t("introduces","general");
x.t("welcome","i-spy");
x.t("started","i-spy");
x.t("procedures","obtain");
x.t("i-spy.","topics");
x.t("1.0","getting");
x.t("1.0","section");
x.t("provisions","welcome");
x.t("section","include:");
x.t("section","introduces");
x.t("accepting","i-spy");
x.t("help","i-spy.");
x.t("help","application");
x.t("application","support");
x.t("topics","section");
x.t("general","i-spy");
}
