function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","create");
x.t("lists","overview");
x.t("lists","section");
x.t("describes","manage");
x.t("create","new");
x.t("deleting","entire");
x.t("items","create");
x.t("items","list");
x.t("new","list");
x.t("new","custom");
x.t("list","deleting");
x.t("list","combining");
x.t("list","removing");
x.t("list","adding");
x.t("gene","lists.");
x.t("overview","viewing");
x.t("include:","managing");
x.t("custom","list");
x.t("entire","list");
x.t("lists.","topics");
x.t("viewing","data");
x.t("combining","existing");
x.t("section","describes");
x.t("section","include:");
x.t("existing","lists");
x.t("data","items");
x.t("removing","data");
x.t("patient","gene");
x.t("topics","section");
x.t("manage","patient");
x.t("adding","new");
}
