function FileData_Pairs(x)
{
x.t("describes","reports");
x.t("advanced","searches");
x.t("results","overview");
x.t("results","high");
x.t("results","i-spy");
x.t("results","viewing");
x.t("results","section");
x.t("overview","search");
x.t("high","order");
x.t("i-spy","returns");
x.t("searches","high");
x.t("search","results");
x.t("viewing","results");
x.t("section","describes");
x.t("section","include");
x.t("reports","search");
x.t("include","following:");
x.t("analyses.","topics");
x.t("topics","section");
x.t("following:","results");
x.t("order","analyses.");
x.t("order","analysis");
x.t("returns","advanced");
x.t("analysis","results");
}
