function FileData_Pairs(x)
{
x.t("user","session.");
x.t("shows","collection");
x.t("results","results");
x.t("results","overview");
x.t("results","high");
x.t("results","generated");
x.t("results","page");
x.t("overview","results");
x.t("overview","viewing");
x.t("overview","view");
x.t("viewed","particular");
x.t("high","order");
x.t("previously","viewed");
x.t("allows","compare");
x.t("search","results");
x.t("search","function");
x.t("collection","reports");
x.t("viewing","results");
x.t("function","high");
x.t("function","search");
x.t("particular","user");
x.t("windows.","view");
x.t("session.","allows");
x.t("reports","previously");
x.t("reports","opening");
x.t("view","results");
x.t("generated","search");
x.t("opening","separate");
x.t("page","shows");
x.t("separate","windows.");
x.t("order","analysis");
x.t("compare","reports");
x.t("analysis","results");
x.t("analysis","function");
}
