function FileData_Pairs(x)
{
x.t("biospecimen","research");
x.t("once","log");
x.t("getting","started");
x.t("appears.","reading");
x.t("link","lower");
x.t("clicking","link");
x.t("right-hand","corner.");
x.t("started","biospecimen");
x.t("legal","rules");
x.t("provisions","once");
x.t("provisions","getting");
x.t("provisions","click");
x.t("provisions","accepting");
x.t("corner.","biospecimen");
x.t("workspace","appears.");
x.t("database","provisions");
x.t("database","workspace");
x.t("database","accepting");
x.t("lower","right-hand");
x.t("road","page");
x.t("click","clicking");
x.t("rules","road");
x.t("accepting","biospecimen");
x.t("research","database");
x.t("page","appears.");
x.t("log","legal");
x.t("reading","provisions");
}
