function FileData_Pairs(x)
{
x.t("once","log");
x.t("getting","started");
x.t("appears.","reading");
x.t("link","lower");
x.t("clicking","link");
x.t("right-hand","corner.");
x.t("i-spy","provisions");
x.t("i-spy","workspace");
x.t("i-spy","accepting");
x.t("started","i-spy");
x.t("legal","rules");
x.t("provisions","once");
x.t("provisions","getting");
x.t("provisions","click");
x.t("provisions","accepting");
x.t("corner.","i-spy");
x.t("workspace","appears.");
x.t("lower","right-hand");
x.t("road","page");
x.t("click","clicking");
x.t("rules","road");
x.t("accepting","i-spy");
x.t("page","appears.");
x.t("log","legal");
x.t("reading","provisions");
}
