function  WWHBookData_Files(P)
{
P.fA("Welcome to I-SPY Online Help","Welcome.1.1.html");
P.fA("Application Support","Application%20Support.2.1.html");
P.fA("Online Help Tips","OnlineHelpBoilerplate.3.1.html");
P.fA("About I-SPY","i-spy_About_I-SPY.4.1.html");
P.fA("About I-SPY","i-spy_About_I-SPY.4.2.html");
P.fA("About I-SPY Functions","i-spy_About_I-SPY.4.3.html");
P.fA("Getting Started with I-SPY","i-spy_Getting_Started.5.1.html");
P.fA("Creating a User Account","i-spy_Getting_Started.5.2.html");
P.fA("Logging In","i-spy_Getting_Started.5.3.html");
P.fA("Accepting I-SPY Provisions","i-spy_Getting_Started.5.4.html");
P.fA("Welcome to I-SPY","i-spy_Getting_Started.5.5.html");
P.fA("Getting Help","i-spy_Getting_Started.5.6.html");
P.fA("Application Support","i-spy_Getting_Started.5.7.html");
P.fA("Logging Out","i-spy_Getting_Started.5.8.html");
P.fA("Conducting an Identifier Lookup","i-spy_ID_Lookup.6.1.html");
P.fA("ID Lookup Overview","i-spy_ID_Lookup.6.2.html");
P.fA("Looking Up a Patient or Sample Identifier","i-spy_ID_Lookup.6.3.html");
P.fA("Displaying/Hiding the Patient Sample Information","i-spy_ID_Lookup.6.4.html");
P.fA("Downloading Patient Sample Information to an Excel File","i-spy_ID_Lookup.6.5.html");
P.fA("Creating a PatientDID List with the ID Lookup","i-spy_ID_Lookup.6.6.html");
P.fA("Conducting Searches","i-spy_Searches.7.1.html");
P.fA("Search Overview","i-spy_Searches.7.2.html");
P.fA("Performing a Clinical Query","i-spy_Searches.7.3.html");
P.fA("Performing an IHC Level of Expression Query","i-spy_Searches.7.4.html");
P.fA("Performing an IHC Loss of Expression Query","i-spy_Searches.7.5.html");
P.fA("High Order Analysis","i-spy_High_Order_Analysis.8.1.html");
P.fA("High Order Analysis Overview","i-spy_High_Order_Analysis.8.2.html");
P.fA("Performing a Class Comparison","i-spy_High_Order_Analysis.8.3.html");
P.fA("Performing a Principal Component Analysis","i-spy_High_Order_Analysis.8.4.html");
P.fA("Performing Hierarchical Clustering Analysis","i-spy_High_Order_Analysis.8.5.html");
P.fA("Performing Correlation Scatter Plot Analysis","i-spy_High_Order_Analysis.8.6.html");
P.fA("Performing Categorical Plot Analysis","i-spy_High_Order_Analysis.8.7.html");
P.fA("Viewing Results","i-spy_View%20Results.9.1.html");
P.fA("Results Overview","i-spy_View%20Results.9.2.html");
P.fA("Using I-SPY Report Icons","i-spy_View%20Results.9.3.html");
P.fA("Search Results","i-spy_View%20Results.9.4.html");
P.fA("Clinical Reports","i-spy_View%20Results.9.5.html");
P.fA("Creating a PatientDID List from a Clinical Report","i-spy_View%20Results.9.6.html");
P.fA("Accessing an NCIA Image from a Clinical Report","i-spy_View%20Results.9.7.html");
P.fA("IHC Level of Expression Search Results","i-spy_View%20Results.9.8.html");
P.fA("IHC Loss of Expression Search Results","i-spy_View%20Results.9.9.html");
P.fA("High Order Analysis Results","i-spy_View%20Results.9.10.html");
P.fA("Class Comparison Report","i-spy_View%20Results.9.11.html");
P.fA("Creating a Gene List (Select Genes toolbar)","i-spy_View%20Results.9.12.html");
P.fA("Resorting Column Results","i-spy_View%20Results.9.13.html");
P.fA("Showing Additional Information","i-spy_View%20Results.9.14.html");
P.fA("Principal Component Analysis Plot","i-spy_View%20Results.9.15.html");
P.fA("Selecting Samples of Interest in a Plot","i-spy_View%20Results.9.16.html");
P.fA("Hierarchical Clustering Report","i-spy_View%20Results.9.17.html");
P.fA("Correlation Scatter Plot","i-spy_View%20Results.9.18.html");
P.fA("Categorical Plot Analysis","i-spy_View%20Results.9.19.html");
P.fA("Managing Lists","i-spy_Manage_Lists.10.1.html");
P.fA("Managing Lists Overview","i-spy_Manage_Lists.10.2.html");
P.fA("PatientDID Lists","i-spy_Manage_Lists.10.3.html");
P.fA("Gene Lists","i-spy_Manage_Lists.10.4.html");
P.fA("Viewing the Data Items in a List","i-spy_Manage_Lists.10.5.html");
P.fA("Removing Data Items to Create a New List","i-spy_Manage_Lists.10.6.html");
P.fA("Combining Existing Lists to Create a New List","i-spy_Manage_Lists.10.7.html");
P.fA("Deleting an Entire List","i-spy_Manage_Lists.10.8.html");
P.fA("Adding a New \u201cCustom\u201d List","i-spy_Manage_Lists.10.9.html");
P.fA("Data Dictionary","i-spy_appa_datadictionary.11.1.html");
P.fA("I-SPY Data Dictionary","i-spy_appa_datadictionary.11.2.html");
P.fA("Patient Demographic Data Dictionary","i-spy_appa_datadictionary.11.3.html");
P.fA("Chemotherapy Summary Data Dictionary","i-spy_appa_datadictionary.11.4.html");
P.fA("On-Study Data Dictionary","i-spy_appa_datadictionary.11.5.html");
P.fA("Post-Surgery Summary Data Dictionary","i-spy_appa_datadictionary.11.6.html");
P.fA("Follow-Up Data Dictionary","i-spy_appa_datadictionary.11.7.html");
P.fA("Response Evaluation Data Dictionary","i-spy_appa_datadictionary.11.8.html");
P.fA("MR Data Dictionary","i-spy_appa_datadictionary.11.9.html");
P.fA("Glossary","i-spy_Glossary.12.1.html");
}
