function FileData_Pairs(x)
{
x.t("create","patientdid");
x.t("related","topics.");
x.t("generating","clinical");
x.t("displays","demographic");
x.t("list","further");
x.t("results","search");
x.t("results","clinical");
x.t("filter","query");
x.t("i-spy","create");
x.t("patientdid","list");
x.t("perform","analysis.");
x.t("further","filter");
x.t("search","results");
x.t("analysis.","information");
x.t("demographic","clinical");
x.t("viewing","results");
x.t("report","displays");
x.t("report","i-spy");
x.t("report","performing");
x.t("reports","viewing");
x.t("reports","clinical");
x.t("pathology","data");
x.t("given","patients.");
x.t("performing","clinical");
x.t("data","given");
x.t("query","perform");
x.t("information","related");
x.t("information","generating");
x.t("patients.","clinical");
x.t("topics.","information");
x.t("clinical","report");
x.t("clinical","reports");
x.t("clinical","pathology");
x.t("clinical","query");
}
