function FileData_Pairs(x)
{
x.t("biospecimen","research");
x.t("data\u00adbase","biospecimen");
x.t("overview","biospecimen");
x.t("include:","biospecimen");
x.t("introduces","biospecimen");
x.t("provides","overview");
x.t("functions.","topics");
x.t("section","include:");
x.t("section","introduces");
x.t("database","biospecimen");
x.t("database","provides");
x.t("database","functions");
x.t("database","functions.");
x.t("research","data\u00adbase");
x.t("research","database");
x.t("research","data");
x.t("data","\u00adbase");
x.t("\u00adbase","section");
x.t("topics","section");
}
