function FileData_Pairs(x)
{
x.t("biospecimen","research");
x.t("user","account");
x.t("support","logging");
x.t("getting","started");
x.t("getting","help");
x.t("obtain","help");
x.t("creating","user");
x.t("account","logging");
x.t("include:","creating");
x.t("logging","accepting");
x.t("introduces","general");
x.t("welcome","biospecimen");
x.t("started","biospecimen");
x.t("procedures","obtain");
x.t("i-spy.","topics");
x.t("provisions","welcome");
x.t("section","include:");
x.t("section","introduces");
x.t("database","getting");
x.t("database","procedures");
x.t("database","provisions");
x.t("database","section");
x.t("accepting","biospecimen");
x.t("research","database");
x.t("help","i-spy.");
x.t("help","application");
x.t("application","support");
x.t("topics","section");
x.t("general","biospecimen");
}
