function FileData_Pairs(x)
{
x.t("biospecimen","research");
x.t("describes","biospecimen");
x.t("look","patient");
x.t("sample","identifiers.");
x.t("sample","identifier");
x.t("overview","looking");
x.t("looking","patient");
x.t("conducting","identifier");
x.t("identifiers","sample");
x.t("include:","lookup");
x.t("identifiers.","topics");
x.t("section","describes");
x.t("section","include:");
x.t("identifier","lookup");
x.t("database","look");
x.t("research","database");
x.t("patient","sample");
x.t("patient","identifiers");
x.t("topics","section");
x.t("lookup","overview");
x.t("lookup","conducting");
x.t("lookup","section");
}
