function FileData_Pairs(x)
{
x.t("describes","i-spy");
x.t("launching","genepattern");
x.t("correlation","scatter");
x.t("hierarchical","clustering");
x.t("categorical","plot");
x.t("overview","performing");
x.t("high","order");
x.t("i-spy","run");
x.t("comparison","performing");
x.t("component","analysis");
x.t("section","describes");
x.t("section","include");
x.t("analyses","topics");
x.t("clustering","analysis");
x.t("performing","correlation");
x.t("performing","hierarchical");
x.t("performing","categorical");
x.t("performing","principal");
x.t("performing","genepattern");
x.t("performing","class");
x.t("principal","component");
x.t("include","high");
x.t("topics","section");
x.t("order","analyses");
x.t("order","analysis");
x.t("run","higher");
x.t("genepattern","analysis");
x.t("class","comparison");
x.t("plot","analysis");
x.t("analysis","launching");
x.t("analysis","overview");
x.t("analysis","high");
x.t("analysis","section");
x.t("analysis","performing");
x.t("scatter","plot");
x.t("higher","order");
}
