function FileData_Pairs(x)
{
x.t("categories","performing");
x.t("p53","query");
x.t("listed","view");
x.t("results","listed");
x.t("results","page");
x.t("overview","conducting");
x.t("overview","search");
x.t("conducting","searches");
x.t("searches","search");
x.t("enables","perform");
x.t("perform","queries");
x.t("search","results");
x.t("search","overview");
x.t("search","function");
x.t("queries","following");
x.t("function","enables");
x.t("report","results");
x.t("level","expression");
x.t("performing","p53");
x.t("performing","ihc");
x.t("performing","clinical");
x.t("ihc","level");
x.t("view","results");
x.t("expression","query");
x.t("page","search");
x.t("query","report");
x.t("query","performing");
x.t("following","categories");
x.t("clinical","query");
}
