function FileData_Pairs(x)
{
x.t("creation","management");
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","lists");
x.t("lists","overview");
x.t("lists","gene");
x.t("lists","further");
x.t("lists","function");
x.t("lists","headings");
x.t("lists","displayed");
x.t("lists","page");
x.t("refine","queries");
x.t("clicking","patientdid");
x.t("overview","managing");
x.t("overview","i-spy");
x.t("gene","lists");
x.t("centralizes","activities");
x.t("i-spy","manage");
x.t("patientdid","lists");
x.t("further","refine");
x.t("study-defined","patientdid");
x.t("queries","facilitate");
x.t("number","lists");
x.t("function","centralizes");
x.t("user-defined","study-defined");
x.t("pertaining","creation");
x.t("displayed","clicking");
x.t("page","minimize");
x.t("facilitate","analysis");
x.t("activities","pertaining");
x.t("note","manage");
x.t("manage","lists");
x.t("management","user-defined");
x.t("minimize","number");
x.t("analysis","note");
}
