function FileData_Pairs(x)
{
x.t("lists","contents");
x.t("summary","data");
x.t("response","evaluation");
x.t("contents","data");
x.t("post-surgery","summary");
x.t("dictionary","response");
x.t("dictionary","post-surgery");
x.t("dictionary","section");
x.t("dictionary","chemotherapy");
x.t("dictionary","pathology");
x.t("dictionary","follow-up");
x.t("dictionary","data");
x.t("dictionary","on-study");
x.t("dictionary","patient");
x.t("dictionary","topics");
x.t("i-spy","data");
x.t("demographic","data");
x.t("section","lists");
x.t("section","include");
x.t("chemotherapy","summary");
x.t("pathology","data");
x.t("follow-up","data");
x.t("include","i-spy");
x.t("evaluation","data");
x.t("data","dictionary");
x.t("on-study","data");
x.t("patient","demographic");
x.t("topics","section");
}
