function FileData_Pairs(x)
{
x.t("related","topics.");
x.t("displays","patients");
x.t("results","search");
x.t("results","viewing");
x.t("results","ihc");
x.t("patientdid","list.");
x.t("search","results");
x.t("patients","patientdid");
x.t("patients","selected");
x.t("selected","ihc");
x.t("select","save");
x.t("viewing","results");
x.t("report","displays");
x.t("level","expression");
x.t("ihc","level");
x.t("additional","information");
x.t("expression","search");
x.t("expression","report");
x.t("expression","search.");
x.t("expression","page");
x.t("search.","ihc");
x.t("page","select");
x.t("information","related");
x.t("save","patients");
x.t("list.","additional");
}
