function FileData_Pairs(x)
{
x.t("biospecimen","research");
x.t("create","biospecimen");
x.t("user","account");
x.t("note:","create");
x.t("getting","started");
x.t("button.","login");
x.t("need","username");
x.t("account","creating");
x.t("account","login");
x.t("creating","user");
x.t("i-spy","need");
x.t("i-spy","logging");
x.t("i-spy","administrator.");
x.t("logging","getting");
x.t("logging","logging");
x.t("logging","log");
x.t("started","i-spy");
x.t("legal","rules");
x.t("assigned","i-spy");
x.t("database","user");
x.t("login","page");
x.t("login","successful");
x.t("enter","username");
x.t("click","submit");
x.t("road","page");
x.t("rules","road");
x.t("username","password");
x.t("research","database");
x.t("page","appears");
x.t("page","enter");
x.t("submit","button.");
x.t("successful","legal");
x.t("password","assigned");
x.t("password","click");
x.t("administrator.","note:");
x.t("log","i-spy");
}
