function FileData_Pairs(x)
{
x.t("analyses:","performing");
x.t("correlation","scatter");
x.t("hierarchical","clustering");
x.t("listed","view");
x.t("categorical","plot");
x.t("results","listed");
x.t("results","page");
x.t("overview","high");
x.t("high","order");
x.t("enables","perform");
x.t("perform","following");
x.t("comparison","performing");
x.t("component","analysis");
x.t("function","enables");
x.t("report","results");
x.t("clustering","analysis");
x.t("performing","correlation");
x.t("performing","hierarchical");
x.t("performing","categorical");
x.t("performing","principal");
x.t("performing","class");
x.t("principal","component");
x.t("view","results");
x.t("page","high");
x.t("order","analysis");
x.t("following","analyses:");
x.t("class","comparison");
x.t("plot","analysis");
x.t("analysis","results");
x.t("analysis","overview");
x.t("analysis","high");
x.t("analysis","function");
x.t("analysis","report");
x.t("analysis","performing");
x.t("scatter","plot");
}
