function FileData_Pairs(x)
{
x.t("getting","started");
x.t("link","upper");
x.t("upper","right-hand");
x.t("steps.","i-spy");
x.t("right-hand","corner.");
x.t("i-spy","logging");
x.t("i-spy","workspace");
x.t("i-spy","follow");
x.t("i-spy","login");
x.t("logging","getting");
x.t("logging","logging");
x.t("logging","log");
x.t("started","i-spy");
x.t("workspace","click");
x.t("corner.","i-spy");
x.t("follow","steps.");
x.t("login","page");
x.t("click","logout");
x.t("page","appears.");
x.t("logout","link");
x.t("log","i-spy");
}
