function FileData_Pairs(x)
{
x.t("describes","perform");
x.t("plots.","topics");
x.t("results","reports");
x.t("overview","performing");
x.t("conducting","searches");
x.t("searches","conducting");
x.t("searches","section");
x.t("include:","search");
x.t("perform","queries");
x.t("search","overview");
x.t("queries","generate");
x.t("section","describes");
x.t("section","include:");
x.t("loss","expression");
x.t("reports","plots.");
x.t("level","expression");
x.t("performing","ihc");
x.t("performing","clinical");
x.t("ihc","loss");
x.t("ihc","level");
x.t("generate","results");
x.t("expression","query");
x.t("query","performing");
x.t("topics","section");
x.t("clinical","query");
}
