package gov.columbia.c2b2.ispy.list;

public enum ListSubType {
    NO_SUBTYPE,IMAGE_CLONE, AFFY_HGU133PLUS2_PROBE_SET, AFFY_100K_SNP_PROBE_SET, DBSNP, GENBANK_ACCESSION_NUMBER, GENESYMBOL, LOCUS_LINK, SNP_PROBESET, PROBE_SET;
}

