function FileData_Pairs(x)
{
x.t("getting","started");
x.t("access","i-spy");
x.t("tabs.","i-spy");
x.t("menu","i-spy");
x.t("i-spy","menu");
x.t("i-spy","i-spy");
x.t("i-spy","functions");
x.t("i-spy","side");
x.t("i-spy","workspace");
x.t("i-spy","tabs");
x.t("enables","quick");
x.t("started","i-spy");
x.t("quick","access");
x.t("functions","tabs.");
x.t("functions","information.");
x.t("side","bar");
x.t("workspace","getting");
x.t("workspace","i-spy");
x.t("workspace","enables");
x.t("information.","access");
x.t("tabs","i-spy");
}
