function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","overview");
x.t("lists","viewing");
x.t("lists","section");
x.t("describes","manage");
x.t("deleting","entire");
x.t("new","lists");
x.t("items","list");
x.t("list","deleting");
x.t("list","exporting");
x.t("gene","lists.");
x.t("overview","adding");
x.t("include:","managing");
x.t("entire","list");
x.t("lists.","topics");
x.t("viewing","data");
x.t("section","describes");
x.t("section","include:");
x.t("exporting","list");
x.t("data","items");
x.t("patient","gene");
x.t("topics","section");
x.t("manage","patient");
x.t("adding","new");
}
