function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("user","account");
x.t("support","logging");
x.t("getting","started");
x.t("getting","help");
x.t("features","used");
x.t("common","features");
x.t("creating","user");
x.t("account","logging");
x.t("i-spy","interfaces");
x.t("i-spy","pages.");
x.t("i-spy","1.0");
x.t("i-spy","provisions");
x.t("pages.","topics");
x.t("include:","creating");
x.t("logging","accepting");
x.t("introduces","i-spy");
x.t("welcome","i-spy");
x.t("started","i-spy");
x.t("1.0","getting");
x.t("1.0","section");
x.t("provisions","welcome");
x.t("section","include:");
x.t("section","introduces");
x.t("accepting","i-spy");
x.t("help","application");
x.t("application","support");
x.t("topics","section");
x.t("navigation","common");
x.t("used","i-spy");
}
