function FileData_Pairs(x)
{
x.t("getting","started");
x.t("link","upper");
x.t("upper","right-hand");
x.t("steps.","i-spy");
x.t("right-hand","corner.");
x.t("logged","i-spy.");
x.t("i-spy","1.0");
x.t("i-spy","workspace");
x.t("i-spy","follow");
x.t("logging","getting");
x.t("logging","logging");
x.t("logging","log");
x.t("started","i-spy");
x.t("1.0","logging");
x.t("workspace","click");
x.t("corner.","logged");
x.t("follow","steps.");
x.t("click","logout");
x.t("logout","link");
x.t("log","i-spy");
}
